package shared;

public class SampleMessage {
	//	@formatter:off
	public static final String SMALL_MSG = "This is a | message with 200 characters\n"
			+  "This is a | message with 200 characters\n"
			+  "This is a | message with 200 characters\n"
			+  "This is a | message with 200 characters\n"
			+  "This is a | message with 200 chara";

	public static final String LARGE_MSG = "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with 2000 characters\n"
			+  "This is a | message with";
	//@formatter:on
}
